### ISSUE TITLE
Blurry header text

### ISSUE THREAD

**Issue by codicem-ex-cinere** [kepano/obsidian-minimal-settings#31]
Since (I believe) Obsidian v0.13.30 was installed, all headers throughout the application became slightly blurry (legible but slightly out of focus). This persists within other vaults with only Minimal theme and Minimal Theme Settings installed, no snippets enabled and everything updated to most recent.

I discovered a solution. It was solved by swapping the order of the two Segoe fonts used for minimal theme via Minimal Theme Settings plugin shown below. Not sure if the order was changed recently in the plugin?

For sections Text Font and Editor Font
default
-apple-system,BlinkMacSystemFont,"Segoe UI Emoji","Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,sans-serif
edited
-apple-system,BlinkMacSystemFont,"Segoe UI","Segoe UI Emoji",Roboto,Oxygen-Sans,Ubuntu,Cantarell,sans-serif

This also coincidently fixed another issue I was having with some emoticons appearing in black and white vs color. That issue persisted without the plugin but with minimal theme enabled so possibly related to a default font set in the theme?

debug info
SYSTEM INFO:
	Obsidian version: v0.13.33
	Installer version: v0.13.31
	Operating system: Windows 10 Pro 10.0.19041
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal
	Snippets enabled: 1
	Safe mode: off
	Plugins installed: 4
	Plugins enabled: 1
		1: Minimal Theme Settings

**Comment by kepano** [comment]
Nothin has changed in Minimal Theme Settings. I believe these issues are fixed in Obsidian v0.13.32

**Comment by codicem-ex-cinere** [comment]
Thanks for the respond. I waited a few days after noticing this issue to see if any bug was fixed on Obsidians end to address this - in addition to googling the issue to death. But even after the recent update 13.33, this is still an issue. I just deleted Minimal theme and Minimal Settings to clear any cache, reloaded Ob and reinstalled the theme and plugin. The header font is still blurry. As you say, you haven't done anything - but perhaps something was done to the main program that requires an update on your end? No idea - just wanted to post this somewhere as I found it was impossible to use with the default blurry font rendering. If you think this should be posted elsewhere please let me know and how I should phrase it - because so far, all I can prove is that it relates to this plugin. Thanks very much..

 Included a before and after "Segoe UI Emoji", "Segoe UI" font switch fix to demo

![minimalsettings-before+after_20220314T143601](https://user-images.githubusercontent.com/101545130/158257833-eca650be-5d47-417d-94ee-207d23e245d7.jpg)

**Comment by codicem-ex-cinere** [comment]
If this seems to be an issue that is unresolvable/not worth looking into because too rare, no problem since I've fixed on my end. Wanted to post, as I said in case others had this rare issue. Thanks

**Comment by kepano** [comment]
I believe that you need to update to the new installer version. This is related to an issue in Electron/Chromium — there is more information in the Obsidian Discord.

**Comment by codicem-ex-cinere** [comment]
I appreciate the note - I had updated via installer to 13.31 after that announcement was made. An installer for 13.33 was not released. ~It sounds like you think it is very likely an obsidian issue so I may bring it up with them. With little experience using electron, logically it seemed best to post to the most likely candidate. Thanks again!

**Comment by kepano** [comment]
The installers for Obsidian can be found here:
https://github.com/obsidianmd/obsidian-releases/releases

I would definitely encourage you to ask in the official Obsidian Discord or forum. From what I have gathered there are a few bugs that are pending a new version of Electron. You can find the pre-release versions above, or you can roll back to a previous version of the installer.

**Comment by codicem-ex-cinere** [comment]
Thanks, the github repo has no installer for 13.33 released.

I checked out the forum, I'll make a quick post there -- and I did my due diligence by checking with you, the plugin author first so this should be more straightforward for them. Cheers.

**Comment by 1039009892** [comment]
I have the save problem. Thanks for your question.
